title: Great Lakes Semiconductor Blog
email: support@glsemi.io
description: >
  Updates and insights on FPGA, Raspberry Pi CM5, and building custom compute hardware.
url: "https://blog.glsemi.io"
theme: minima
email: support@glsemi.io
url: glsemi.io
markdown: kramdown
